# Generated by Django 3.2.9 on 2022-10-22 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_alter_stoke_officer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stoke',
            new_name='Stock',
        ),
    ]
