# Generated by Django 3.2.9 on 2022-10-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_rename_stoke_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
