# Generated by Django 3.2.9 on 2022-10-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0004_alter_bin_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='officer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
