# Generated by Django 3.2.9 on 2022-10-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0005_alter_stock_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=10),
        ),
    ]
