# Generated by Django 3.2.9 on 2022-10-26 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0007_auto_20221025_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bin',
            name='status',
        ),
    ]
