# Generated by Django 3.2.9 on 2022-11-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0012_auto_20221104_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='list_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
