# Generated by Django 3.2.9 on 2022-11-04 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0013_alter_bin_list_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='created',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
