# Generated by Django 3.2.9 on 2022-11-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0015_bin_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stoke_keeper',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
